# Generated by Django 6.1 on 2026-09-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('author', models.CharField(default='Datum Metrics Team', max_length=100)),
                ('category', models.CharField(default='Architecture & Engineering', max_length=100)),
                ('published_at', models.DateField(help_text='Article publication date')),
                ('read_time', models.CharField(default='5 min read', max_length=40)),
                ('intro', models.TextField(help_text='Short abstract / teaser text')),
                ('content', models.TextField(help_text='Full post content in markdown or HTML')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('client_name', models.CharField(max_length=150)),
                ('industry', models.CharField(default='Enterprise Technology', max_length=100)),
                ('category_tag', models.CharField(default='SaaS & Cyber-Security', max_length=100)),
                ('impact_metric', models.CharField(help_text='e.g. +340% Throughput & Zero Breach Record', max_length=150)),
                ('summary', models.TextField(help_text='Executive summary of the client outcome')),
                ('challenge', models.TextField(blank=True, help_text='The core architectural or security challenge')),
                ('solution', models.TextField(blank=True, help_text='The solution engineered by Datum Metrics')),
                ('results', models.TextField(blank=True, help_text='Measurable business & technical results')),
                ('tech_stack', models.CharField(blank=True, default='Django, React, Postgres, Redis, AWS', max_length=255)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. 99.99% or 10B+', max_length=50)),
                ('label', models.CharField(help_text='e.g. Platform Uptime', max_length=150)),
                ('description', models.CharField(blank=True, help_text='Short detail', max_length=255)),
                ('icon', models.CharField(choices=[('shield', 'Cyber Security Shield'), ('code', 'Web Development Code'), ('layers', 'SaaS Layers'), ('cpu', 'AI / ML Processing'), ('database', 'Data Analytics'), ('cloud', 'Cloud Infrastructure')], default='database', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Company Metric',
                'verbose_name_plural': 'Company Metrics',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('service_interest', models.CharField(blank=True, default='General Inquiry', max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('contacted', 'Contacted'), ('archived', 'Archived')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('category', models.CharField(default='Web Development', help_text='e.g. Web Development, SaaS, Cyber-Security, Data Analytics, AI/ML, Cloud Infrastructure', max_length=100)),
                ('badge', models.CharField(blank=True, default='Enterprise Offering', max_length=60)),
                ('summary', models.TextField(help_text='Short service summary description')),
                ('description', models.TextField(blank=True, help_text='Detailed HTML/Markdown service description')),
                ('tech_stack', models.CharField(default='Python, Django, React, AWS, Docker, Kubernetes, Cyber Security Audit', help_text='Comma-separated tech keywords', max_length=255)),
                ('icon', models.CharField(default='globe', help_text='Icon identifier (e.g. globe, server, shield-check)', max_length=50)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature bullet points')),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=150)),
                ('quote', models.TextField()),
                ('metric_badge', models.CharField(blank=True, default='Verified Client', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'id'],
            },
        ),
    ]
