# Generated by Django 6.1 on 2026-09-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_brand', models.CharField(default='Datum Metrics', max_length=80)),
                ('hero_badge_text', models.CharField(default='LIVE INFRASTRUCTURE MONITOR', help_text='Short badge label shown above the hero headline', max_length=120)),
                ('hero_headline_line1', models.CharField(default='Engineering High-Throughput', help_text='First line of the large hero headline', max_length=200)),
                ('hero_headline_line2', models.CharField(default='Web, SaaS & Cyber-Security', help_text='Second line – shown in red gradient', max_length=200)),
                ('hero_subtext', models.TextField(default='Datum Metrics Ltd builds resilient digital platforms. Pure Django backends, reactive Inertia interfaces, zero-trust cloud architectures, and streaming telemetry pipelines.')),
                ('hero_cta_primary', models.CharField(default='Explore Solutions', max_length=80)),
                ('hero_cta_secondary', models.CharField(default='Schedule Technical Audit', max_length=80)),
                ('contact_section_heading', models.CharField(default='Ready to Upgrade Your Architecture?', max_length=200)),
                ('contact_section_subtext', models.TextField(default='Connect directly with our lead systems architects to evaluate throughput bottlenecks, execute SOC2 security audits, or engineer custom multi-tenant SaaS platforms.')),
                ('contact_bullet_1', models.CharField(default='Direct technical review by Principal Engineers', max_length=200)),
                ('contact_bullet_2', models.CharField(default='Mutual NDA execution prior to source review', max_length=200)),
                ('contact_bullet_3', models.CharField(default='Full-stack migration from legacy monoliths to pure Django', max_length=200)),
                ('footer_tagline', models.CharField(default='Building resilient, high-throughput digital infrastructure.', max_length=200)),
                ('footer_copyright', models.CharField(default='© 2026 Datum Metrics Ltd. All rights reserved.', max_length=200)),
                ('services_page_heading', models.CharField(default='Enterprise Solutions', max_length=200)),
                ('services_page_subtext', models.TextField(default='Scalable, secure, and high-throughput architectures for modern enterprises.')),
                ('case_studies_page_heading', models.CharField(default='Client Transformations', max_length=200)),
                ('case_studies_page_subtext', models.TextField(default='Proven engineering outcomes across industries.')),
                ('insights_page_heading', models.CharField(default='Technical Insights & Architecture', max_length=200)),
                ('insights_page_subtext', models.TextField(default='Deep-dives into Python/Django concurrency, zero-trust hardening, sub-millisecond telemetry, and reactive frontends.')),
                ('contact_page_heading', models.CharField(default='Start a Conversation', max_length=200)),
                ('contact_page_subtext', models.TextField(default='Our team of systems architects is ready to assess your infrastructure and design a solution tailored to your scale.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TechPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. PYTHON 3.13', max_length=100)),
                ('url', models.URLField(blank=True, help_text='Optional link (not shown on marquee)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tech Partner / Marquee Tag',
                'verbose_name_plural': 'Tech Partners / Marquee Tags',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal team notes on this inquiry'),
        ),
    ]
