# Generated by Django 6.1 on 2026-08-25 13:56

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blog Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('author', models.CharField(default='Datum Metrics Team', max_length=100)),
                ('date', models.DateField(verbose_name='Post date')),
                ('read_time', models.CharField(default='5 min read', max_length=30)),
                ('intro', models.TextField(help_text='Short abstract / teaser text')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blog Post Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CaseStudyIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Case Study Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CaseStudyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('client_name', models.CharField(max_length=150)),
                ('industry', models.CharField(default='Enterprise Technology', max_length=100)),
                ('impact_metric', models.CharField(help_text='e.g. +340% Throughput & Zero Breach Incident Record', max_length=100)),
                ('summary', models.TextField()),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Case Study Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ServiceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction overview for all services')),
            ],
            options={
                'verbose_name': 'Service Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('category', models.CharField(default='Web Development', help_text='Primary category: Web Development, SaaS, Cyber-Security, Data Analytics, AI/ML, Cloud Infrastructure', max_length=100)),
                ('badge', models.CharField(blank=True, default='Enterprise Offering', max_length=50)),
                ('summary', models.TextField(help_text='Short service summary description')),
                ('tech_stack', models.CharField(default='Wagtail, Python, Django, React, AWS, Docker, Kubernetes, Cyber Security Audit', help_text='Comma-separated tech keywords', max_length=255)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Service Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 7), ('stats_counter', 16), ('services_grid', 28), ('metrics_calculator', 31), ('case_studies', 38), ('testimonial', 40), ('call_to_action', 45)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Top badge text e.g. 'Next-Gen Data & Cloud Infrastructure'", 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main hero title', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Hero description', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Explore Services', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': '#services', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Schedule Consultation', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': '#contact', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('metric_badge', 0), ('title', 1), ('subtitle', 2), ('primary_cta_text', 3), ('primary_cta_url', 4), ('secondary_cta_text', 5), ('secondary_cta_url', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Performance & Impact By The Numbers', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'default': 'Engineered for high reliability, enterprise security, and massive throughput.', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 99.99% or 10B+', 'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Platform Uptime', 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short detail', 'required': False}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('shield', 'Cyber Security Shield'), ('code', 'Web Development Code'), ('layers', 'SaaS Layers'), ('cpu', 'AI / ML Processing'), ('database', 'Data Analytics'), ('cloud', 'Cloud Infrastructure')]}), 14: ('wagtail.blocks.StructBlock', [[('number', 10), ('label', 11), ('description', 12), ('icon', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('title', 8), ('subtitle', 9), ('stats', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Our Core Solutions', 'required': True}), 18: ('wagtail.blocks.TextBlock', (), {'default': 'From custom Web Development and scalable SaaS to bulletproof Cyber-Security and Data Analytics.', 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'required': True}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Cyber-Security, Web Development, SaaS', 'required': True}), 21: ('wagtail.blocks.TextBlock', (), {'required': True}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Enterprise Ready', 'required': False}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('globe', 'Web Development'), ('cloud-saas', 'Software as a Service (SaaS)'), ('shield-check', 'Cyber-Security'), ('bar-chart', 'Data Analytics & BI'), ('brain', 'Artificial Intelligence & ML'), ('server', 'Cloud & DevOps')]}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Feature point'}), 25: ('wagtail.blocks.ListBlock', (24,), {}), 26: ('wagtail.blocks.StructBlock', [[('title', 19), ('category', 20), ('description', 21), ('badge', 22), ('icon', 23), ('features', 25), ('link_url', 6)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {}), 28: ('wagtail.blocks.StructBlock', [[('title', 17), ('subtitle', 18), ('services', 27)]], {}), 29: ('wagtail.blocks.CharBlock', (), {'default': 'Interactive ROI & Security Impact Estimator', 'required': True}), 30: ('wagtail.blocks.TextBlock', (), {'default': 'Estimate your performance boost, security posture rating, and operational cost savings with Datum Metrics.', 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('title', 29), ('subtitle', 30)]], {}), 32: ('wagtail.blocks.CharBlock', (), {'default': 'Featured Success Stories', 'required': True}), 33: ('wagtail.blocks.TextBlock', (), {'default': 'How Datum Metrics drives transformative outcomes for industry leaders.', 'required': False}), 34: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. SaaS & Cyber-Security', 'required': True}), 35: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 10x Scalability & Zero Breaches', 'required': True}), 36: ('wagtail.blocks.StructBlock', [[('client_name', 19), ('project_title', 19), ('category_tag', 34), ('impact_metric', 35), ('summary', 21), ('link_url', 6)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {}), 38: ('wagtail.blocks.StructBlock', [[('title', 32), ('subtitle', 33), ('case_studies', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'Verified Client', 'required': False}), 40: ('wagtail.blocks.StructBlock', [[('quote', 21), ('author', 19), ('role', 19), ('company', 19), ('metric_badge', 39)]], {}), 41: ('wagtail.blocks.CharBlock', (), {'default': 'Ready to Scale Your Digital Infrastructure?', 'required': True}), 42: ('wagtail.blocks.TextBlock', (), {'default': 'Partner with Datum Metrics for modern Web Development, resilient SaaS architectures, and enterprise Cyber-Security.', 'required': True}), 43: ('wagtail.blocks.CharBlock', (), {'default': 'Start Your Project', 'required': True}), 44: ('wagtail.blocks.CharBlock', (), {'default': '#contact', 'required': True}), 45: ('wagtail.blocks.StructBlock', [[('title', 41), ('text', 42), ('button_text', 43), ('button_url', 44)]], {})}),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
