# Generated by Django 6.1 on 2026-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sitesettings_techpartner_contactinquiry_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='contact@datummetrics.com', help_text='Clickable mailto address shown on the contact page', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_guarantee_1',
            field=models.CharField(default='No junior hand-offs — all projects led by Senior Architects', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_guarantee_2',
            field=models.CharField(default='Full IP ownership transfer upon project milestones', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_guarantee_3',
            field=models.CharField(default='Fixed-scope or dedicated velocity squad engagements', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_guarantee_title',
            field=models.CharField(default='Enterprise Guarantee', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_protocol_1_label',
            field=models.CharField(default='Direct Architectural Desk', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_protocol_2_label',
            field=models.CharField(default='Confidentiality Assured', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_protocol_2_text',
            field=models.CharField(default='Mutual NDAs executed before accessing codebase repositories or architecture diagrams.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_protocol_3_label',
            field=models.CharField(default='Guaranteed Response SLA', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_protocol_3_text',
            field=models.CharField(default='Lead systems engineers reply within 24 business hours with initial analysis.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_protocol_title',
            field=models.CharField(default='Engagement Protocols', max_length=100),
        ),
    ]
