# Generated by Django 6.1 on 2026-09-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sitesettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contact_subtext',
            field=models.CharField(default='Direct architect review within 24 business hours.', help_text='Small subtext shown under the contact email in the footer.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_tech_badges',
            field=models.CharField(default='DJANGO 5.1+, DRF v1 API, INERTIA REACT', help_text='Comma-separated tech badge labels shown in the footer brand column.', max_length=300),
        ),
    ]
