"""
Django settings for datum_metrics project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    # Unfold — must be declared before django.contrib.admin
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",

    "home",
    "rest_framework",
    "django_filters",
    "inertia",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "inertia.middleware.InertiaMiddleware",
]

ROOT_URLCONF = "datum_metrics.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "datum_metrics.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "datum_metrics_ltd",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "127.0.0.1",
        "PORT": "3306",
        "OPTIONS": {
            "unix_socket": "/opt/lampp/var/mysql/mysql.sock",
            "charset": "utf8mb4",
            "init_command": "SET NAMES utf8mb4 COLLATE utf8mb4_general_ci;",
        },

    }
}



# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/6.1/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Inertia Settings
INERTIA_LAYOUT = "base_inertia.html"

# Django REST Framework Settings
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 12,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}


# ---------------------------------------------------------------------------
# Unfold Admin Configuration
# https://unfoldadmin.com/docs/configuration/settings/
# ---------------------------------------------------------------------------

from django.templatetags.static import static  # noqa: E402
from django.urls import reverse_lazy           # noqa: E402

UNFOLD = {
    "SITE_TITLE": "Datum Metrics",
    "SITE_HEADER": "Datum Metrics Admin",
    "SITE_URL": "/",
    # Square icon used in browser tab + sidebar collapsed state
    "SITE_ICON": {
        "light": lambda request: static("admin/img/dm_icon.svg"),
        "dark":  lambda request: static("admin/img/dm_icon.svg"),
    },
    # Full horizontal wordmark logo used in expanded sidebar
    "SITE_LOGO": {
        "light": lambda request: static("admin/img/dm_logo_light.svg"),
        "dark":  lambda request: static("admin/img/dm_logo_dark.svg"),
    },
    "SITE_SYMBOL": "bar_chart",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "datum_metrics.admin_helpers.environment_callback",
    "DASHBOARD_CALLBACK": "datum_metrics.admin_helpers.dashboard_callback",
    "THEME": "dark",
    "COLORS": {
        "font": {
            "subtle-light": "107 114 128",
            "subtle-dark":  "156 163 175",
            "default-light": "17 24 39",
            "default-dark":  "243 244 246",
        },
        # Brand-red primary palette
        "primary": {
            "50":  "255 245 245",
            "100": "254 226 226",
            "200": "254 202 202",
            "300": "252 165 165",
            "400": "248 113 113",
            "500": "239 68 68",
            "600": "220 38 38",
            "700": "185 28 28",
            "800": "153 27 27",
            "900": "127 29 29",
            "950": "69 10 10",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Content",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Site Settings",
                        "icon": "settings",
                        "link": reverse_lazy("admin:home_sitesettings_changelist"),
                    },
                    {
                        "title": "Blog Posts",
                        "icon": "article",
                        "link": reverse_lazy("admin:home_blogpost_changelist"),
                        "badge": "home.admin_helpers.blogpost_badge",
                    },
                    {
                        "title": "Services",
                        "icon": "handyman",
                        "link": reverse_lazy("admin:home_service_changelist"),
                    },
                    {
                        "title": "Case Studies",
                        "icon": "cases",
                        "link": reverse_lazy("admin:home_casestudy_changelist"),
                    },
                    {
                        "title": "Testimonials",
                        "icon": "format_quote",
                        "link": reverse_lazy("admin:home_testimonial_changelist"),
                    },
                ],
            },
            {
                "title": "Metrics & Partners",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Company Metrics",
                        "icon": "bar_chart",
                        "link": reverse_lazy("admin:home_companymetric_changelist"),
                    },
                    {
                        "title": "Tech Partners",
                        "icon": "hub",
                        "link": reverse_lazy("admin:home_techpartner_changelist"),
                    },
                ],
            },
            {
                "title": "Leads",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Contact Inquiries",
                        "icon": "mail",
                        "link": reverse_lazy("admin:home_contactinquiry_changelist"),
                        "badge": "home.admin_helpers.new_inquiries_badge",
                    },
                ],
            },
            {
                "title": "Authentication",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Groups",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}
